version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:80"
networks:
  default:
    external:
      name: eshoponweb_default
